//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFServiceWebRole1
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_profile
    {
        public int eventID { get; set; }
        public string userID { get; set; }
        public string day { get; set; }
        public string month { get; set; }
        public string year { get; set; }
        public string eventName { get; set; }
    }
}
